### ISSUE TITLE
OAuth for Yelp API

### ISSUE THREAD

**Issue by ossrapaport-zz** [ossrapaport/first_date_app#10]
@harimohanraj89 @DrRobotmck @WilliamfShaw @bigtone1284 

Current User Story: As a user I want to be able to search for a good restaurant, suggested from my and my date's interests, in a convenient location to have a good date.

I am trying to make requests to the Yelp API (Version 2). In order to do so, I need OAuth access. We have obtained a Consumer Key, a Consumer Secret, a Token, and a Token Secret from Yelp. We also have a timestamp generator and a randomly selected nonce. The file we are working on is server.js, but I haven't pushed the code yet. Here is a screenshot: 
![screen shot 2015-04-01 at 12 05 15 pm](https://cloud.githubusercontent.com/assets/10967603/6945389/68e258e0-d867-11e4-8b11-856c076fcd93.png)

We have looked at the Yelp docs and for examples of using Yelp with Node on GitHub. We have also talked to a number of students in WDI Wonka who recommended Omniauth, so we looked at everyauth and passport but do not know how to implement them or if they'd work. We would appreciate help making this API request using OAuth. Thank you.

**Comment by harimohanraj89** [comment]
What branch are you working on? Also, push your current code so we can view it.

**Comment by ossrapaport-zz** [comment]
Fixed this by using the yelp npm
